### ISSUE TITLE
cnn acceleration with tensorly runs slower than without decompostion?

### ISSUE THREAD

**Issue by tutuxh** [JeanKossaifi/tensorly-notebooks#10]
when I run the notebook (05_pytorch_backend/cnn_acceleration_tensorly_and_pytorch.ipynb), I find that the tucker decomposition convolutional layer runs slow. The decomposed VGG16 runs slower than the original VGG16? why? how to evaluate the runtime and calculate the speedup?

**Comment by JeanKossaifi** [comment]
Which system did you use? (GPU, pytorch/tensorly version, etc)?
There are many things that come into play. The rank used, etc. 
You can have more details on the method in the [original paper](https://arxiv.org/abs/1511.06530).

**Comment by tutuxh** [comment]
Thanks for your reply. I use pytorch 1.0 and tensorly 0.4.4 with a GPU TITAN Xp. The tucker decomposition is tested. While the tensor ranks is set to [conv.weight..size(0)//32, conv.weight.size(1)//32], the model inference time is still slow. I think the decomposed 3 conv layer forward may take much time than expected. Is there any other reasons?

**Comment by JeanKossaifi** [comment]
Sorry for the long delay, I completely lost track of this!

I agree, the theoretical gains don't always translate into actual speedups -- it's very depending on the software and hardware: it can vary a lot depending on the size of the kernels, on the rank of the decomposition, but also on the GPU and CUDA version. You can check the original papers to see the setting the authors used.

If you are still interested in this, we released [TensorLy-Torch](http://tensorly.org/torch/dev/) which implements general tensor layers in PyTorch.

**Comment by JeanKossaifi** [comment]
Closing for now -- TensorLy-Torch should improve speed a lot. Feel free to open an issue in the main tensorly repo if you identify any bottleneck!
