### ISSUE TITLE
Need little help regarding regression after autoscaling

### ISSUE THREAD

**Issue by Mohamed0gad** [JeanKossaifi/tensorly-notebooks#11]
Hi, 
I have spectroscopic X tensor of 3-way data, and corresponding y vector. My steps as follow:
Spectral matrix 2D (samples x wavelengths) ===> Autoscale, add derivative spectra as the third dimension. Next,  I use this 3-way data tensor in tucker regression vs the vector of concentration

I tried to construct a Tucker regression model using X without autoscaling but the  RMSE was large however the y_predicted were similar y vector, when tried to autoscale  X data using StandardScaler().fit_transform RMSE became accurate but after adding the mean of the y vector to the y_predicted (element wise). 

I cant figure out why this happens, I appreciate any help, thanks.

Additionally, I appreciate if you suggested a source to understand this regression type "for beginner in 3-way data"

Thanks

**Comment by JeanKossaifi** [comment]
Hi @Mohamed0gad,
Sorry to have missed this - we don't yet support pipelines (but plan to), so it might not work as expected. 
The safest might be apply the scaling and the regression for now.

**Comment by JeanKossaifi** [comment]
Closing here, feel free to open an issue on the main TensorLy repository!
