### ISSUE TITLE
Sparse example notebooks need updates on import

### ISSUE THREAD

**Issue by danielyahn** [JeanKossaifi/tensorly-notebooks#12]
Since kruscal_tensor has been deprecated per https://github.com/tensorly/tensorly/commit/984e00d179cbb0da29afb346f706953779997d1f

I had to change
`from tensorly.contrib.sparse.kruskal_tensor import kruskal_to_tensor`
to 
`from tensorly.contrib.sparse.cp_tensor import kruskal_to_tensor`

for the notebooks under 07_pydata_sparse_backend/ to work

**Comment by JeanKossaifi** [comment]
Thanks for reporting @danielyahn and sorry for the delay.
This has been fixed in bd3444506e341508d191c86c30d8fde85f020146.
