### ISSUE TITLE
Adding a license file?

### ISSUE THREAD

**Issue by nzmora** [JeanKossaifi/tensorly-notebooks#5]
Hi,

It would be helpful if you added a license file, to communicate how you want to share this code. 
Thanks!

**Comment by JeanKossaifi** [comment]
Hi @nzmora,
Good point - what type of sharing do you have in mind?
Note that TensorLy itself is BSD-licensed

**Comment by nzmora** [comment]
I'm not an expert on licenses, but I think BSD 2/3 clauses are good. I prefer Apache License 2.0.  
Thanks!

**Comment by JeanKossaifi** [comment]
I meant how/what are you intending to share? :)

**Comment by nzmora** [comment]
I guess I read what I wanted to read, not what you asked ;-)

I saw @jacobgil 's blog (https://jacobgil.github.io/deeplearning/tensor-decompositions-deep-learning) and thought that maybe I can reference/reuse/borrow-ideas-from some of his work (using tensorly and tensorly-notebooks) in https://github.com/NervanaSystems/distiller. That's what got me to ask about the license of the notebooks, but I figure the license is necessary for anyone wishing to use the notebooks in some non-private capacity.

**Comment by JeanKossaifi** [comment]
Nice library! :)

From my side, feel free to reuse the code. As I mentioned TensorLy is BSD-licensed anyway, and these notebooks are mainly examples :)
When I get some time I'll look into what license would be appropriate. In any case, would be great to see tensor methods-based compression in distiller!

**Comment by nzmora** [comment]
Sure thing - if the license issue becomes a problem, I'll give you a nudge.  I may have pulled the trigger too early ;-)
