### ISSUE TITLE
My question

### ISSUE THREAD

**Issue by DimanChuancey** [JeanKossaifi/tensorly-notebooks#9]
I want to know whether the ‘shape’ and the ‘rank’ in the tucker decomposition are always the same. Could their value be different？How are their value determined？
I'm a beginner in this area. Hope to reply to me.

**Comment by JeanKossaifi** [comment]
Hi @DimanChuancey sorry about the delay. 
Rank is the rank of the decomposition so you can set it as you like. 
In general lower than the shape (low-rank weighths), you could have a rank higher than the shape (over-parametrized). You can have a look at the [doc](http://tensorly.org/dev/modules/generated/tensorly.decomposition.tucker.html#tensorly.decomposition.tucker). If you want a good intro to tensor decomposition I highly recommend the great survey by Kolda and Bader, “Tensor Decompositions and Applications”, SIAM REVIEW, vol. 51, n. 3, pp. 455-500, 2009.

**Comment by DimanChuancey** [comment]
> Hi @DimanChuancey sorry about the delay.
> Rank is the rank of the decomposition so you can set it as you like.
> In general lower than the shape (low-rank weighths), you could have a rank higher than the shape (over-parametrized). You can have a look at the [doc](http://tensorly.org/dev/modules/generated/tensorly.decomposition.tucker.html#tensorly.decomposition.tucker). If you want a good intro to tensor decomposition I highly recommend the great survey by Kolda and Bader, “Tensor Decompositions and Applications”, SIAM REVIEW, vol. 51, n. 3, pp. 455-500, 2009.

Thanks! Good wishes!
